##Pytorch:
## !nvidia-smi # check gpu or not

# Tensor are the main buliding block for deeplearning data, in pytorch everthing represent as tensor.

for scaler value or single value
scaler = torch.tensor(7) # result = 7 

# see the dimensions
#! torch.ndim    # note scaler has no dimension 

#To get number from scaler is or tensor to python int value:
scaler.item()  # result = 7

# vecor has magnitude and direction, it has more than 1 number.
vector = torch.tensor([7,7]) # tensor([7,7])

# diff between dimension and shape 
ndim means number of pair of closing breakets [] and shape is (2)

# metrix 
matrix  = torch.tensor([[1,2],[3,4]] # shape is (2,2) and ndim is 2

# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [1,3,4],
                        [5,4,5]]]) # shape is (1,3,3) means i channel or example, 3 rows and 3 columns

# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4) # shape will be (3,4) and ndim =2

random_tensor = torch.rand(size=(1,3,3)) # 3 dimension, shape(1,3,3)

# zeros and ones 
# create zeros 
zeros = torch.zeros(size=(3,4))

# create ones 
ones = torch.ones(size=(3,4)) # default data type is torch.float32

# create range of tensors:
range = toch.range(0,10)
range = torch.arange(0,10)
range = torch.arange(start= 0,end=1000,step=100) # start with 0 and then take step =100 and then go till 999

# create tensor like 
#ex.  have tensor.arange(0,10) and i have to create zeros same shape of given range 
zero_ = tensor.zeros_like(input=tensor.arange(0,10))

# Tensor types
float_32_type = torch.tensor([3.,2.,3.],dtype=None) # default is torch.float32

# imp params when create tensor is 
dtype # float32 bit it is single precision, 16 bit is half precision, bfloat16,8,64 bit or doubleTensor,int64 is longtensor
device #cpu or cuda
requires_grad # bool True or False for training it is True and False for prediction, if true, python to track gradience when tensor go through numerical calculation.

#! Note:Some operation will run error when two tensor have diff datatype exlongdata type tensor.mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
# detail about tensor
tensor.dtype, tensor.shape,tensor.device 

# add somethin in tensor 
tensor = torch.tensor([1,2,3])
tensor = tensor+10   # result [11,12,13]
tensor = tensor*10  or torch.mul(tensor,10)
tensor = tensor-10

# matrix multiplication 
element-wise multiplication [1,2,3] * [1,2,3] = [1,4,9]
matrix multiplication(dot product) torch.matmul([1,2,3],[1,2,3]) or [1,2,3]@[1,2,3] = [14]

# to transpose the tensor 
tensor.T

## Tensor Aggregation(min,max,mean,sum)
tens = torch.randn([1,3,3])
tens.min(),tens.max(),tens.mean()

# find position(index) in tensor that have minimum and maximum value
tens = torch.argmin()
tens = torch.argmax()

# reshape, view , stack, Squeeze, Unsqueeze, 
tensor.reshape(a,b)
# reshape and view is same both share the same memory so ex. if we change in z. changes also appear in x

# arrange tensor top of each other using stack
torch.stack(tensor,dim=0) # row wise dim=0, column wise dim=1.
2 type vstack and hstack
# squeeze : from 2d to 1d and and unsqueeze: from 1d to 2d, ex have range and unsqueeze row wise then dim=0 and if column wise then dim=1.


# shift axis ex [224,224,3] here 3 is channel of image so i need that 0th index.
tensor = torch.tensor([224,224,3])
res = tensor.permute(2,0,1) #  res = [3,224,224]

# python Tensors & Numpy
Numpy to tensor -> torch.from_numpy(ndarray).type(torch.float32)
# Tensor to numpy -> tensor.numpy()

#! default numpy data type is float64 so when convert this into tensor then also type is float64

# manual_seed:
torch.manual_seed(43) # used to avoud reand value generated by randn command we get same value at every run. it is psudo random number generator
torch.randn([1,3,3])

# check for gpu is available 
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# count number of device
torch.cuda.device_count()

#move tensor to device:
tensor_on_gpu = tensor.to(device)

# if tensor is on GPU, cant transform it to numpy, we have to first convert it to cpu and then transform to numpy
tensor.cpu().numpy()




# example for model training:
epochs =10

for epoch in range(epochs):
    # set the model to train
    model_0.train()

    # forward pass 
    y_pred = model_0(X_train)

    # calculate loss
    loss = loss_fn(y_pred,y_train)

    # optimizer zero grad # because forward pass i got which model have made mistack in prediction during training. so calculate loss 
    optimizer.zero_grad() # now based on loss need to update weights and bias to reduce loss thats why need to previous accumulation of gradient =0. because pytorch bydefault accumulate gradient 

    loss.backward() # beck ward calculation gradient is calculated for update weights

    optimizer.step() # This is action phase gradient calculated by loss.backward() and this step is adjust the weights and bias to minimize the loss. this will be accumulated

    model.eval() # turns off tracking. Using model.eval() is crucial for obtaining reliable and reproducible results when evaluating a trained model on validation or test datasets, or when performing inference on new data. It ensures that the model's behavior is consistent and reflective of its learned capabilities, without the regularization effects(Dropout layers are deactivated) or batch-dependent statistics(Batch Normalization layers use learned running statistics) present during training.

    with torch.inference_mode():
        test_pred = model_0(X_test)
        test_loss = loss_fn(test_pred,y_test)

    if epoch % 10 ==0:
        print(f"epoch:{epoch} | Loss: {loss} | test loss: {test_loss}")
        print(model_0.state_dict())


# for plotting need to convert tensor to numpy 
torch.tensor(lst).numpy()


# save mode: three method.
torch.save() - allows you save pytorch object in pythons' pickle format
torch.load() - allows you to load saved pytorch object
torch.nn.Module.load_state_dict() - load models saved state dictionary

# for saving the model's state_dict
model_save_path = 'pytorch_model.pth'
#save
torch.save(obj = model_0.state_dict(),f=model_save_path)


# load model
new_model = LinearfRFegressionModel()
new_model.load_state_dict(torch.load(f=model_save_path))



###############################

class LinearRegressionModel_V2(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.linear_layer = nn.Linear(in_feature=1,
                                      out_features=1)

        self.linear_layer_1 = nn.Linear(in_feature=1,
                                      out_features=1)
                        
    
    def forward(self,x: torch.Tensor)->torch.Tensor:
        return self.linear_layer_1(self.linear_layer(x))

model_1 = LinearRegressionModel_V2()
model_1.state_dict() # to see params

loss_fn = nn.L1loss()

optimizer = nn.optim.SGD(params=model_1.parameters(),lr=0.001)

# 2nd way to create model
model_01 = nn.Sequential(nn.Linear(in_features=1,out_features=1),
                         nn.Linear(in_features=1,out_features=1)) # we can add number of layers in this aswell.
model_01.state_dict()


# training and prediction 
nn.manual_seed(42)
epochs = 200

X_train = X_train.to(device)
X_test = X_test.to(device)
y_train = y_train.to(device)
y_test = y_test.to(device)

for epoch in range(epochs):
    model_1.train()

    pred = model_1(X_train)

    loss = lossfn(pred,y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    model_1.eval() # remove dropout layer and batch normalization etc

    with torch.inference_mode():
        y_pred = model_1.predict(X_test)
        test_loss = lossfn(y_pred,y_test)

    if epoch % 10 ==0:
        print(f"epoch: {epoch} | loss :{loss} | test loss: {test_loss}")


# to get params
model_1.state_dict()

# prediction 
model_1.eval()
with torch.inferencemode():
    pred_y = model_1.predict(X_test)

# now we can plot y_test and pred_y
# at time of prediction pred_y type is torch.Tensor need to convert type cuda to cpu or convert this into numpy 
pred_y.cpu().numpy()


# save model dict
model_path = 'model_1.pth'
torch.save(obj=model_1.state_dict(),f=model_path)

# load this state dict in new model
model_2 = LinearRegressionModel_V2()
model_2.load_state_dict(torch.load(model_path))




# make prediction 
model_2.to(device)

model_2.eval() # eval model 
with model_2.inference_mode():
    model_2_pred = model_2.prediction(X_test)



def accuracy(y_true,y_pred):
    correct = torch.eq(y_true,y_pred).sum().item()
    acuuracy = (correct/len(y_true)) * 100

# Binary-classification:
loss_fn = BCEWithLogitLoss() 

optimizer = torch.optim.SGD()

X_train,y_train = X_train.to(device), y_train.to(device)
X_test,y_test = X_test.to(device), y_test.to(device)

epochs = 100
for epoch in range(epochs):
    # train the model
    model_0.train()

    # make prediction 
    y_train_pred = model_0(X_train)

    # Calcuolate the loss
    y_logits = y_train_pred.squeeze() 
    train_loss = loss_fn(y_logits,y_train)

    # for accuracy 
    y_pred = torch.round(torch.softmax(y_logits))
    accuracy = accuracy(y_train,y_pred)

    #zero grad
    optimizer.zero_grad()

    #backward propagation to calculate gradient 
    loss.backward()

    optimizer.step() # update weight and bias

    model_0.eval() # if dropout or normalization layer used in training then it remove for inference 

    with torch.inference_mode():
        y_test_pred = model_0.predict(X_test)
        y_test_logit = y_test_pred.squeeze()
        
        # calculate the loss
        test_loss = (y_test_logit,y_test)
        # calculate the accuracy
        test_accuracy = accuracy(y_test,torch.round(torch.sigmoid(y_test_logit)))

    if epoch % 10 ==0:
        print(f'Epoch: {epoch} | accuracy: {accuracy} | loss: {train_loss} | test_accuracy: {test_accuracy} | test_loss: {test_loss}')



# non Linear Model

class CircleModel(nn.Module):  
    def __init__(self):
        super().__init__():
            self.linear_layer_1 = nn.Linear(in_features=2,out_features=10)
            self.linear_layer_2 = nn.Linear(in_features=10,out_features=10)
            self.linear_layer_3 = nn.Linear(in_features=10,out_features=1)
            self.relu = nn.ReLU()

    def forward(self,x):
        return self.linear_layer_3(self.relu(self.linear_layer_2(self.relu(self.linear_layer_1(x)))))


# multiclass classification
class MultiClass(nn.Module):
    def __init__(self,input_features,output_features,hidden_features=8):
        super().__init__():
        self.multi_calss_layer = nn.Sequential(
            nn.Linear(in_features=input_features,out_features=hidden_features),
            nn.ReLU(),
            nn.Linear(in_features=hidden_features,out_features=hidden_features),
            nn.ReLU(),
            nn.Linear(in_features=hidden_features,out_features=output_features),
        )
        
    def forward(self,x):
        return self.multi_calss_layer(x)

# For prediction
device = 'cuda' if torch.cuda.isavailable() else "cpu"
model = MultiClass().to(device)

loss_fn = CrossEntropyLoss()
optimizer = torch.optim.SGD(params=model.parameters(),lr=0.01)

epochs = 100

for epoch in range(epochs):
    model.train()
    
    #get logits
    y_train_pred = model.(X_train).squeeze()

    # convert logit to probability for multi class use softmax
    y_train_pred = nn.softmax(y_train_pred,dim=1)
    # to get class as index
    y_train_pred = torch.argmax(y_train_pred,dim=1)
    # find loss 
    loss = loss_fn(y_train_pred,y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    model.eval()

    with torch.inference_mode():
        y_test_pred = model.predict(X_test).squeeze()
        y_test_pred = nn.softmax(y_test_pred,dim=1)
        y_test_pred = torch.argmax(y_test_pred,dim=1)

        test_loss = lossfn(y_test_pred,y_test)




##! CNN

import torch 
from torch import nn 
from torchvision import dataset 
from torchvision import transformers
from torchvision.transformers import ToTensor

from matplotlib.pyplot as plt

train_data = dataset.FashinMNIST(root='data',# path
                    train=True, # torch vision has dataset available in train and test, do we want train
                    download = True, #do we want download
                    transform = ToTensor(),
                    target_transform = None
                    )

test_data = dataset.FashionMNIST(root='data',# path
                                 train=False,# do you want train dataset, need test dataset
                                 download=True,
                                 transform =ToTensor(),
                                 target_transform=None  
                                 )

# to get the classes of data : train_data.classes
# get class with idex: train_data.class_to_idx
# get only class lables : train_data.tagret 
# there are other params .

# imput image
image,label = train_data[0]#  FashionMNIST has shape [1,28,28]
# matplotlb requires only hight and width
image.squeeze() removes 1 dimension from [1,28,28], result = [28,28]
plt.imshow(image.squeeze())


## To see images using plotly multiple images 4 row , 4 column with label 
class_names = train_data.classes
torch.manual_seed(42)
plt.figure(figsize=(9,9))
row,col = 4,4
for i in range(1,row*col+1):
  image_idx = torch.randint(0,len(train_data),size=(1,)).item()
  image,lable = train_data[image_idx]
  plt.subplot(row,col,i)
  plt.imshow(image.squeeze(),cmap='gray')
  plt.title(label=class_names[lable])
  plt.axis(False)

# note: when you print dataset information you get:
# Dataset FashionMNIST
#     Number of datapoints: 60000
#     Root location: data
#     Split: Train
#     StandardTransform
# Transform: ToTensor()

# so to load dataset use DataLoader turns out dataset into python iterable.
from torch.utils.data import DataLoader


train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

# because train_dataloader and test_dataloader is object type , if you want to see the shape

train_dataloader_features,label = next(iter(train_dataloader))
train_dataloader_features.shape(),label.shape()


# function if file exist then ok else download file
import requests
from pathlib import Path 

if Path('function_file.py').is_file():
    print('helper function is exist')
else:
    request = requests.get(url)
    with open('function_file.py','wb') as f:
        f.write(request.content)
        

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(lr=0.01,params=model_0.parameters())

# training 
epochs = 3
from tqdm.auto import tqdm
from timeit import default_timer as timer
training_time_start  = timer()

for epoch in tqdm(range(epochs)):
    train_loss = 0
    train_acc = 0
    for batch,(X,y) in enumerate(train_dataloader)
        # train 
        model_0.train()
        pred_train_y = model_0(X)

        # calculate loss
        loss = loss_fn(pred_train_y,y)

        train_loss+=loss

        # Optimizer grad
        optimizer.zero_grad()

        # Loss Backward
        loss.backward()

        accuracy = accuracy(y,pred_train_y.argmax(dim=1))

        #optimizer step
        optimizer.step()

        if batch % 400 ==0:
            print(f"Looked at {batch * len(X)}/{len(train_dataloader.dataset)} samples.")

    # train loss
    train_loss /= len(train_dataloader)
    #accuracy
    accuracy /= len(train_dataloader)


    test_loss =0
    test_acc =0
    model_0.eval()

    with torch.inference_mode():
        for x_test , y_test in test_dataloader:
            y_test_pred = model_0.predict(x_test) # get logits

            test_loss += loss_fn(y_test_pred,y_test) 

            test_acc+= accuracy(y_test,y_test_pred.argmax(dim=1))   

        test_loss /= len(test_dataloader)
        test_acc /= len(test_dataloader)

    print(f"Train Loss:{train_loss}, Train Accuracy: {accuracy} | Test Loss: {test_loss}, Test Accuracy: {test_acc}")


training_time_end  = timer()

total_training_time = print_train_time(start=training_time_start,end=training_time_end,device=str(next(model_0.parameter().device))


###  CNN layer buliding 


class FashionMNIST(nn.Module):
    def __init__(self,input_shape:int,hidden_units:int,output_shape:int):
        super().__init__():
        self.conv_layer_1 = nn.Sequential(
                            nn.Conv2d(in_channel = input_shape,
                                      out_channel = hidden_units,
                                      kernel_size = 3,
                                      stride=1,
                                      padding=1),
                            nn.ReLU(),
                            nn.Conv2d(in_channel=hidden_units,
                                      out_channel=hidden_units,
                                      kernel=3,
                                      stride=1,
                                      padding=1),
                            nn.ReLU(),
                            nn.MaxPool2d(kernel_size=2)
        )
        self.conv_layer_2 = nn.Sequential(
                            nn.Conv2d(in_channel=hidden_units,
                                        out_channel=hidden_units,
                                        kernel_size=3,
                                        padding = 1,
                                        stride=1)
                            nn.ReLU(),
                            nn.Conv2d(in_channel=hidden_units,
                                      out_channel=hidden_units,
                                      kernel_size=3,
                                      stride=1,
                                      padding=1)
                            nn.ReLU(),
                            nn.MaxPool2d(kernel_size=2)
        )
        self.classifier_layer = nn.Sequential(nn.Flatten(),
                                              nn.Linear(in_features=, # there is trick to calculate this 
                                                        out_features=output_shape))

    def forward(self,x):
        x = self.conv_layer_1(x)
        x = self.conv_layer_2(x)
        x = self.classifier_layer(x)
        return x


torch.manual_seed(42)
model_0 = FashionMNIST(input_shape=1,hidden_units=10,output_shape=len(class_name).to(device))


                            
    


# cnn
def make_prediction(model: torch.nn.Module,data: list, device: torch.device = device):
    pred_probability = []
    model.to(device)
    model.eval()
    with torch.inference_mode():
        for sample in data:
            sample = torch.unsqueeze(sample,dim=0).to(device)
            
            # prediction 
            pred_logit = model(sample)

            # get prediction probability 
            pred_prob = torch.softmax(pred_logit.squeeze(),dim=0)

            pred_probability.append(pred_prob.cpu())

    return torch.stack(pred_probability)


# get random sample from test data 
import random 
random.seed(42)

test_samples = []
test_labels =[]

for sample, label in random.sample(list(test_data),k=9):
    test_samples.append(sample)
    test_labels.append(label)

test_samples[0].shape
pred_prob = make_prediction(model,test_samples)

pred_class_lst = pred_prob.argmax(dim=1)

# pred_class_lst result compare with test_labels

#plot :
plt.figure(figsize=(9,9))
row=9
col=9

for i,sample in enumerate(test_samples):
    plt.subplot(row,col,i+1)
    plt.imshow(sample.squeeze(),cmap='gray')

    pred_label = class_names[pred_class_lst[i]]

    actual_label = class_names[test_labels[i]]
    
    title_text = f"Pred: {pred_label} | Truth: {actual_label}"

    if pred_label == actual_label:
        plt.title(title_text,fontsize=10,c='g')
    else:
        plt.title(title_text,fontsize=10,c='r')
    plt.axis(False)


# for test_dataloader
y_preds =[]

model.eval()
with torch.inference_mode():
    for X,y in tqdm(test_dataloader,desc='making predictions.....'):
        X,y = X.to(devide),y.to(device)

        y_logit = model(X)
        y_pred = torch.softmax(y_logit.squeeze(dim=0).argmax(dim=1))
        y_preds.append(y_pred.cpu())

# concat list of prediction into tensor
y_pred_tensor = torch.cat(y_preds)





















